local spec = require('cmp-core.core.spec')
local Keymap = require('cmp-core.kit.Vim.Keymap')
local LineContext = require('cmp-core.core.LineContext')

describe('cmp-core.core', function()
  describe('LineContext', function()
    for _, mode in ipairs({ 'i', ':' }) do
      describe(mode, function()
        it('should create cursor context', function()
          spec.reset()
          Keymap.spec(function()
            Keymap.send(mode):await()
            Keymap.send('foo+'):await()
            local context = LineContext.create()
            assert.is.equal(4, context.character)
            assert.is.equal('foo+', context.text)
            assert.is.equal('+', context.char)
            Keymap.send('<Esc>'):await()
          end)
        end)
      end)
    end
  end)
end)
